### ISSUE TITLE
Ensure Notifications

### ISSUE THREAD

**Issue by eak24** [AguaClara/aguaclara_tutorial#11]
I have now several times added an issue to a repo only to find out that someone on the team didn't see it! We need to make sure that everyone has [email notifications turned on]( https://github.com/settings/notifications) on their github account AND they are [watching all the repos they are part of](https://help.github.com/articles/watching-and-unwatching-repositories/). We need to add this to the tutorials (@kevinjuan25 ) and @AguaClara/leadership needs to have everyone this semester turn on these notifications.

**Comment by janakshah373** [comment]
I can just include this in the email I send out tomorrow with the links so Kevin wouldn't have to update the tutorial.

**Comment by eak24** [comment]
The tutorial should still be updated so that this happens in future semesters so that you don't have to remind people. That is the point of the tutorial. Thanks @jhs373 for sending that out!

**Comment by kevinjuan25** [comment]
Check the tutorial page for GitHub. I added a section on watching a repository. It's not very detailed as it's not a difficult task. Let me know if it suffices

**Comment by janakshah373** [comment]
@kevinjuan25 the section looks good to me
