### ISSUE TITLE
Python Basics Question #6

### ISSUE THREAD

**Issue by Thomas-Bradford** [AguaClara/aguaclara_tutorial#13]
For the graph for question #6, do we plot Reynolds number in relation to viscosity, or in relation to temperature in Kelvin? The instructions say:

"You want to see how the Reynolds Number changes as viscosity changes due to a change in temperature from 0 to 200<sup>o</sup>C. Create a plot of Reynolds Number against Temperature in Kelvin to show a relationship."

**Comment by kevinjuan25** [comment]
Temperature
