### ISSUE TITLE
Python Basics Question 6

### ISSUE THREAD

**Issue by JonathanDavidHarris** [AguaClara/aguaclara_tutorial#14]
When I attempt to save my plot using `plt.savefig('./Images/ReyKelvinPlot.png')` it did not work. I have an image folder already, but it keeps giving me this error message: FileNotFoundError: [Errno 2] No such file or directory: './Images/ReyKelvinPlot.png'

**Comment by fletchapin** [comment]
@jdh345 Have you tried quitting python completely and then reopening it with your personal repository being the only project? I ran into this issue last night with someone and just restarting fixed it

**Comment by eak24** [comment]
@JonathanDavidHarris @kevinjuan25 @fletchapin did this get determined and fixed? Re-open if the cause was determined.
