### ISSUE TITLE
Not able to recognize aide_design on atom

### ISSUE THREAD

**Issue by MehrinSelimgir** [AguaClara/aguaclara_tutorial#15]
Hi, 
I deleted and reinstalled Anaconda however, now I cannot run any of my python code on atom. Please see screenshot below for the error message. I've also tried updating aide_design through command prompt and anaconda prompt but I get the following errors. 
![capture1](https://user-images.githubusercontent.com/31317823/36235701-2cd6ae92-11c0-11e8-9556-f31bc6a524c1.PNG)
![capture2](https://user-images.githubusercontent.com/31317823/36235702-2ce9fd4e-11c0-11e8-98be-7c75766004e1.PNG)

**Comment by canaandelgado** [comment]
I am having the same issue :/

**Comment by kevinjuan25** [comment]
We can check on this issue in lab next week

**Comment by eak24** [comment]
Did this get fixed? I'm closing now... reopen if necessary
