### ISSUE TITLE
Improve video chat in the lab

### ISSUE THREAD

**Issue by eak24** [AguaClara/aguaclara_tutorial#16]
@monroews Even at my house, where I am the only one on a 50/50 network, the video calls still often cut out, suggesting to me that there is some internet connectivity issues there in the lab. Especially in the design lab where the AIDE teams meet. Is there any chance someone could check on that? Also, when meeting with a large group it would be lovely to have a bluetooth thing that connects and has good omni-directional mics and speakers. As you can see from our attempt to meet with Juan, such technical difficulties can completely destroy any chance at good communication! And we could just have a dedicated spot for it in the lab. [Here's one for $100](https://www.amazon.com/Jabra-Wireless-Bluetooth-Softphone-Packaging/dp/B00AQUO5RI/ref=sr_1_1?ie=UTF8&qid=1519746295&sr=8-1&keywords=conference+call+bluetooth#customerReviews). I think it is well worth $100-$200, especially considering the app teams have no other expenses!

**Comment by monroews** [comment]
I checked with Cameron. The wireless should be fine in the design lab. He suggests using ZOOM (Cornell's preferred option for conferencing). He also recommended a USB conference mike.  Did you want this to connect to a phone or to a laptop? If laptop, then USB. If phone, then bluetooth.

**Comment by eak24** [comment]
Sometimes phone, sometimes computer. 90% of laptops these days have bluetooth. I think the one I linked is pretty good - it's battery powered (15 hours of life), has omni-directional mics and speakers, and here's a snippet from a reviewer:

> So, with that said, how does it work?
> This thing is fantastic! The sound quality is very clear with no echo or distortion of any kind. In the very first meeting, we were in a break room and more people attended than anticipated. I was positioned 10-12 feet from the unit. At one point I asked a question of a participant on the phone and he was able to hear me clearly and respond. The unit is round and has omni-directional microphones, so people in the room can be heard clearly by people on the phone regardless where they are seated in the room. Frankly, I would take this unit over almost any speakerphone or conference phone that I have used in any conference room. In fact, my whole team now has them, as well as several folks from one of our partner companies that attended some meetings where this device was used. I have now participated both as a presenter in the room with the unit, and as a remote participant. The sound quality is superb in both cases.
> 

I'll try with Zoom today and report back here.

**Comment by eak24** [comment]
@monroews just had another challenging video call. It was better than the past, but still not great. We used Zoom. It's impossible for me to do a good job with lousy video chat! Also, I chatted with Rose earlier in the day and the calls were crystal clear (HD!) so I know it is not on my side. I'm sure the internet there is slower than it should be when there are multiple teams in there working. Could we ask Cameron what could be done to improve the internet? And also the bluetooth conference speaker would be lovely...

**Comment by monroews** [comment]
Bluetooth conference speaker will arrive on Friday. Should be ready for any Friday afternoon meetings.
I've made a followup request to Cameron to look for a solution to get better internet.

**Comment by monroews** [comment]
The internet problem can be solved by using one of the desktop computers in the design lab. They have wired internet and so internet should be fast. We could easily turn the design lab into a conference room by adding a wall mounted screen with a camera. Let me know if I should move on that option.

**Comment by eak24** [comment]
@monroews you make an excellent point about the wired connection. Unfortunately we need the students' computers to be able to chat with me because they are often screensharing and don't have the suite of programs that they are used to on the desktops. However, your observation got me thinking that we should have a long ethernet cable in the design lab that can be plugged into the students' computers. A lot of the modern laptops don't have ethernet jacks because they are too bulky, but they do have USB jacks, so I wonder if we could get [this adapter](https://www.amazon.com/StarTech-USB31000S-Gigabit-Ethernet-Network/dp/B0095EFXMC/ref=sr_1_1_sspa?ie=UTF8&qid=1519913584&sr=8-1-spons&keywords=ethernet%2Bto%2BUSB&th=1) and somehow permanently connect it to the long ethernet cable so it doesn't wander off (wire tie the ethernet cable to the body of the adaptor?) How does that sound? As for a screen + camera option for the design lab, I think that makes sense. It would be useful when teams of 3+ students are trying to pair-program and I'm on the other line. I wonder if we could put a ~28-32" monitor at the end of the table at the windows with the camera directly above it, and have the hdmi, camera usb and ethernet usb easily available for the students to plug in their own machines? We certainly don't want a dedicated video chat computer - that would just cause more confusion.

**Comment by monroews** [comment]
I've ordered the adapter. Will arrive on Monday.
There are monitors in the room that could easily be connected to a laptop with the right adaptor.

**Comment by eak24** [comment]
Do we have the right adaptor? Problem is, those monitors are currently connected to desktops, right? And very often both desktops are being used and I'm trying to chat with students at the same time, so even if we were switching the monitor from desktop to laptop all the time, we still wouldn't have enough monitors in that room...

**Comment by monroews** [comment]
I think we have plenty of monitors. Perhaps one of the AIDE students can tell me which adaptor I need to purchase to use with one of those monitors.

**Comment by eak24** [comment]
We need the capability to support laptops with HDMI and thunderbolt outputs. I don't know what the input for the monitor your thinking of is, so I can't recommend an adaptor. If it were DVI, I recommend getting these two: [HDMI](https://www.amazon.com/AmazonBasics-Input-Output-Adapter-Cable/dp/B014I8UQJY/ref=sr_1_2_sspa?s=electronics&ie=UTF8&qid=1519917630&sr=1-2-spons&keywords=hdmi+to+dvi&psc=1) and [thunderbolt](https://www.amazon.com/Cable-Matters-DisplayPort-ThunderboltTM-Compatible/dp/B00DJCB83O/ref=sr_1_2_sspa?s=electronics&ie=UTF8&qid=1519917684&sr=1-2-spons&keywords=thunderbolt+to+dvi&psc=1)

**Comment by monroews** [comment]
hdmi-hdmi cable ordered to plug in directly to the display
hdmi to thunderbolt adaptor 
logitech camera placed on the monitor.
Everything should be here by Monday.

**Comment by eak24** [comment]
Thanks! I'm closing this now.
