### ISSUE TITLE
Implement doctest team wide

### ISSUE THREAD

**Issue by eak24** [AguaClara/aguaclara_tutorial#17]
@kevinjuan25 I think we should implement doc testing team-wide. I think it would be useful to any teams that are trying to make functions that are reusable.

# What is doctesting, you ask??
check out the following function:
```python
def add(a,b):
    """
    >>> add(5,10)
    15
    """
    return a+b
```
Notice the >>> in the docstring? This indicates that the user could put it into their python interpreter and get the immediately following response. Doctest automates this, ensuring the documentation is up to spec. And it's a simple way to test code. Please see my [gist](https://gist.github.com/ethan92429/bdb61ccdf352e1fbf560e80dc5ee4481) about it. And please try it out! Also, we should insist teams are using it ASAP.

Also could you add a section about it in your tutorial?

Thanks!!!

**Comment by kevinjuan25** [comment]
@ethan92429 Sounds like a great idea! I'll add it to the tutorial as soon as I can, and we'll make sure all teams make use of it.

**Comment by kevinjuan25** [comment]
@ethan92429 See first draft of doctest in the wiki and provide feedback please.

**Comment by eak24** [comment]
Hey @kevinjuan25 this looks great! Just looked it over. Thanks for writing it up so quickly!
