### ISSUE TITLE
Unable to push to GitHub from Atom

### ISSUE THREAD

**Issue by Thomas-Bradford** [AguaClara/aguaclara_tutorial#18]
I've been able to push files in the past. Recently, I've received this error whenever I try to push a file:

"Unable to push
remote: Permission to AguaClara/filter-constrictions.git denied to Thomas-Bradford.
fatal: unable to access 'https://github.com/AguaClara/filter-constrictions.git/': The requested URL returned error: 403"

What's the best way to fix this issue?

**Comment by kevinjuan25** [comment]
Try removing the repository and re-cloning it.

**Comment by Thomas-Bradford** [comment]
I've tried that twice, but the same error occurs. Is there some other way to fix it?

**Comment by eak24** [comment]
Try  this: https://stackoverflow.com/a/7771927/5136799
