### ISSUE TITLE
Fall 2018 Updates

### ISSUE THREAD

**Issue by kevinjuan25** [AguaClara/aguaclara_tutorial#19]
# Additions to the Tutorial File
* Add section/problem asking students to [doctest](https://github.com/AguaClara/aguaclara_tutorial/wiki/Tutorial:-Python-Basics#doctest)
* Consider splitting the file into two files: one for Markdown exclusively and another for python exclusively
* Add section/problem asking students to use `aguaclara_research` package
* Unit checking (See [Discussion Post](https://github.com/orgs/AguaClara/teams/aide_design/discussions/6) in @AguaClara/aide_design)

# Wiki Pages
* Add page on using `aguaclara_research`
* Add page on unit checking?

# Updates to Code Standards
* All code should include doctesting
* Unit checking necessary for research teams?

# Fall 2018 Training Suggestions
* Students who have completed the training document in Spring 2018 should complete a new one in Fall 2018 due to addition of doctesting, use of `aguaclara_research`, and unit testing

@AguaClara/team-leads @ethan92429 @monroews @eldorbekpulatov Edit post as necessary or make suggestions on what should be included or removed from the tutorials

**Comment by oliver-leung** [comment]
These tasks have been reorganized into their own issues. We won't be adding pages on `aguaclara_research` to this wiki - instead, @HannahSi will be updating instead the `aguaclara_research` wiki, and we will make a link from this wiki to the `aguaclara_research` wiki.
