### ISSUE TITLE
Create Git Bash Tutorial

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/aguaclara_tutorial#20]
Add wiki page with tutorial on how to use git bash generally.  Pushing, pulling, and other useful commands.  Maybe add deeper explanations of GitHub functionality here as well to explain.

**Comment by oliver-leung** [comment]
[The tutorial](https://github.com/AguaClara/aguaclara_tutorial/wiki/Running-Git-from-the-Command-Line) looks great! I might reshuffle the info around when I restructure the wiki, but it's a great resource on the topic.
