### ISSUE TITLE
Reorganize Tutorials

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/aguaclara_tutorial#26]
Before the semester starts we should reorganize this repository to best support new members.  After discussions, we think there should be 3 distinct folders within this repository (names subject to change):

* General Tutorials: All tutorials required for all new members to complete
* Research Tutorials: Tutorials on specific parts of research work, but applicable to members of multiple subteams.  Should be well organized by focus (fabrication, coding, particle removal, etc.)
* AguaClara_research tutorials: tutorials on using aguaclara_research code (installation, plotting, etc.)

Subteam specific tutorials should be written in the wiki on their repositories

@oliver-leung you were working on organization before, would you be able to continue working on this?  @HannahSi and I can help you as well

**Comment by IanCullings** [comment]
Also a reminder that we should talk with the team leads about writing and reviewing these tutorials before the semester starts

**Comment by oliver-leung** [comment]
Just so we remember, we discussed yesterday that we'd organize _general/research_ tutorials under [the aguaclara_tutorial wiki](https://github.com/AguaClara/aguaclara_tutorial/wiki), and put `aguaclara_research` tutorials under [its wiki](https://github.com/AguaClara/aguaclara_research/wiki).

I'm currently reorganizing the existing tutorials in this wiki, and I'm adding/removing information from them as I go.
