### ISSUE TITLE
Add section on doctesting

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aguaclara_tutorial#27]
Add a section describing the process of doctesting Python code. It should be a compilation of the information in [this article](https://docs.python.org/3/library/doctest.html).

(Originally from issue #19)

**Comment by IanCullings** [comment]
This already exists under the [Good Coding Practices](https://github.com/AguaClara/aguaclara_tutorial/wiki/Good-Coding-Practices).  Should we have a distinct tutorial for just doctesting though?

**Comment by oliver-leung** [comment]
Oh that's true. The tutorial is pretty dense, though, so I think I'll go ahead and cut it down.
