### ISSUE TITLE
AguaClara Interactive Tutorial Suggestions

### ISSUE THREAD

**Issue by kevinjuan25** [AguaClara/aguaclara_tutorial#3]
Leave any suggestions you have for the AguaClara Interactive Tutorial `.md` file.

**Comment by clare45** [comment]
Make a mention that to add the image you need to get a page that only has the image rather than the name of the file in the repository, alternately the trick y'all used with putting them in an image folder in the wiki

**Comment by kevinjuan25** [comment]
@ceo45 Can you clarify? Are you talking about inserting an image from a webpage?

**Comment by clare45** [comment]
Once it's uploaded into my repository, I need to open the image in a new tab and use that url rather than the one of the repository which is not intuitive.  Is that clearer? @kevinjuan25

**Comment by kevinjuan25** [comment]
@ceo45 Got it!

**Comment by kevinjuan25** [comment]
@ceo45 When you open the image by clicking on the file name, you can also right click on the image to copy the address. As shown below:
![copyimageaddress](https://user-images.githubusercontent.com/31362150/35999913-5794660e-0cef-11e8-936b-f14cd15a69e7.png)

I'll add this picture in to make it clearer

**Comment by eak24** [comment]
@ceo45 @kevinjuan25 do you guys know that you can link to images locally? (Like with a relative link to something that is inside the repo?) Read [this](https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2) please if not!

**Comment by kevinjuan25** [comment]
@ethan92429 Yep! We have that set up for this wiki, but if students are writing a report in a Markdown file, wouldn't the best way for them to store images be in a folder within the repo?

**Comment by eak24** [comment]
Yes, but they can still link to that with a relative link (relative to the repo directory), ie. /images/butterfly.jpg instead of uploading and then linking (like https://some.stuff.online.com), which might cause strange behavior.

**Comment by kevinjuan25** [comment]
Ok, I'll go back and add that to the tutorial

**Comment by clare45** [comment]
@kevinjuan25 

in the Atom installation, there's a sentence my teammate found unclear as he's reinstalling it:

'When you run the installation this time around you'll need to check off the box that says "Add Anaconda to my PATH environment variable"'

He was confused by 'check off', I knew it to mean checked, but that wording could be ambiguous.
