### ISSUE TITLE
Machine Shop Training

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/aguaclara_tutorial#31]
Hi @monroews, @HannahSi and @ahong731 were talking about machine shop training for new members and we wanted your input.   

Since working with the bottom geometry they have needed to use a lathe to make cuts, which neither of them can use.  While we had Tim's help, we might not always have him available, and it would be best if we could do this ourselves in the future to be respectful of their time.

A couple of questions about this:
* Has there ever been machine shop training for AguaClara members before?  
* If not, how do you feel about trying this next semester?  I know other project teams have them (I have done them before) and we could probably join on.  I think there is a small cost per person.
* Another thing to consider is that all Mechanical Engineers take a course on using the machine shop and should have those skills around sophomore to junior year.  Could we just utilize them for shop work?

If this sounds good with you, I'll move forward with the Fall team leads to get this implemented.

**Comment by monroews** [comment]
I recommend that we try to minimize our use of the machine shop. We can probably develop a method to fabricate the sed tank bottom geometry that will not require any machine shop time.

**Comment by oliver-leung** [comment]
We discussed that, because of the number of MechE students who are already trained, and Tim and Paul in the machine shop, that it's not necessary to offer training on this.
