### ISSUE TITLE
Fix images

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aguaclara_tutorial#33]
@ahong731 

The images in the [Turbidimeter Cleaning](https://github.com/AguaClara/aguaclara_tutorial/wiki/Turbidimeter-Cleaning) page are not appearing. This is because you have them linked locally to the `/Images` folder in the wiki repository, and Github wiki's don't like that.

To make them appear, change the image link to:
```
https://github.com/AguaClara/aguaclara_tutorial/wiki/IMAGE-PATH-HERE
```
The image path would be `/Images/Turbidimeter-Maintenance/CleanTurb1.jpeg` and so on - you'll have to do this for any future images you add.

**Comment by ahong731** [comment]
Oh I see - I was trying to figure out how to do it but obviously did not figure it out.
Thanks so much! Will change it tomorrow at lab.
