### ISSUE TITLE
Training resources for using Git and GitHub

### ISSUE THREAD

**Issue by zoemaisel** [AguaClara/aguaclara_tutorial#34]
This is a really cool training game for git and github! Maybe we can incorporate it into trainings? https://learngitbranching.js.org/?NODEMO 

Also I am not sure who is working on this so I just assigned TLs!

**Comment by oliver-leung** [comment]
This is a great resource! However, it's a bit long and goes into a lot more detail than most team members would need.

How about if we take the most important points from the training game, add them to the current Git/Github tutorial, then have a link to the training game at the end of the tutorial?

**Comment by zoemaisel** [comment]
That sounds like a great idea! Are you the person working on updating the tutorial?

**Comment by oliver-leung** [comment]
Yup, I've been reorganizing it and revising the info in the tutorials.
