### ISSUE TITLE
Ideally people would use a pipenv environment within the reports

### ISSUE THREAD

**Issue by eak24** [AguaClara/aguaclara_tutorial#35]
So far, we don't record anywhere what version of aide_design or numpy or any of the packages, for that matter, that are used to generate a given report. This is asking for trouble! What it means is that in a couple years, when you want to "run" an old report, you'll have to do some archaeology to figure out which version did what. The standard fix (and this would probably help with other problems we're having) is to employ a python environment. It should be standard practice to have an environment for each research team. It is easier than it may sound. [Just a couple commands here. ](https://docs.pipenv.org/) @HannahSi @IanCullings

**Comment by eak24** [comment]
This can probably be included within the interactive tutorial.

**Comment by IanCullings** [comment]
@ethan92429 one question just to clarify, do we need to use virtual environments when running basic code in markdown files, like in our reports?  Especially if we may be calling functions from aide_design or aguaclara_research?

**Comment by eak24** [comment]
@IanCullings Hannah and I discussed this. It sounds like it should get tabled for the research team. This came from my fear that last year there were updates to aide_design that would break research team reports. The problem was that it was never documented anywhere what precise version a report was actually using. Therefore it is possible that old reports would simply not work anymore and one would have to dig through the code to determine what dependencies made it sing. However, it sounds like virtual environments are too much to throw at the research team! They already have more than enough with the other changes. :) I'm going to go ahead and close this with the note that we maybe should pursue it in the future!
