### ISSUE TITLE
Python wiki page recommendations

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/aguaclara_tutorial#36]
In [this wiki page heading](https://github.com/AguaClara/aguaclara_tutorial/wiki/Python#debugging) under number 3, the link to "open an issue on Github" links to github.com, which seems confusing to new members. I recommend linking it the the issues page on this repo and advising that they place it their issues in the relevant repositories.

**Comment by juanchon998** [comment]
@oliver-leung

**Comment by oliver-leung** [comment]
Fixed
