### ISSUE TITLE
sigfig is depricated

### ISSUE THREAD

**Issue by monroews** [AguaClara/aguaclara_tutorial#4]
I believe that we are no longer using the sigfig function. Turns out that pint has a built in feature for controlling significant figures. Unfortunately I don't recall how the pint code works.

**Comment by kevinjuan25** [comment]
@monroews Finally found the answer to this courtesy of [Ethan on StackOverflow](https://stackoverflow.com/questions/46367187/pint-significant-figures-precision)

**Comment by eak24** [comment]
@kevinjuan25 Sorry for the hunt effort! I already put this into the code by default... see [here.](https://github.com/AguaClara/aide_design/commit/5e5fcd1bb80cb3858e011393cdd86e0071e5a8d4) There is a default setting of 4 figures, or you can specify a number of sigfigs.
