### ISSUE TITLE
Python Training Ideas

### ISSUE THREAD

**Issue by kevinjuan25** [AguaClara/aguaclara_tutorial#5]
## What is the best way to teach the entire team Python for AguaClara work in a reasonable amount of time with as little stress as possible for the students and teachers?

My current ideas are:
* Office hours style where subteams sign up to meet with one of several "experts" to walk through the interactive tutorial; however, this would require subteams to look over the static Python tutorial on the wiki before the meeting.
* Monday night lecture -- I don't like this idea because lecturing on coding is tough and boring, and sitting through a lecture on that material is equally, if not more boring. Additionally, having 60 people try to work with Python is a headache as we've learned from trying to get 20 people to just download Atom.
* Have STLs go through the static and interactive tutorial, and train their team on Python. I can still hold office hours for teams that are having trouble. This may need a leadership meeting where STLs learn about Python, or would be a fairly demanding task for STLs.

**Comment by CynthiaTChan** [comment]
I think this could be done with people who know Python but are not necessarily STLs. Everyone who took 4540 last semester should be good, all the CS peeps, and some random others could help teach and this does not need to be a very formal activity.

**Comment by sidneylok** [comment]
@cc2467 I agree with you (assuming you are talking about the third option that Kevin proposed). Looking over the subteams now, it seems that there should be at least one person with experience in Python in each team so this is definitely feasible.

**Comment by kevinjuan25** [comment]
@cc2467 @sgl38 Perhaps we can ask STLs and 4540 students who know Python to walkthrough the static tutorial with their teams, and members can attempt the interactive tutorial in groups or individually depending on their preference. I can then offer time for teams to get extra help in office hours style. Thoughts?

**Comment by sidneylok** [comment]
@kevinjuan25 I like this setup as it also encourages communication and bonding within the subteam! Nothing like getting closer together over frustrations with code. Now the only thing is I don't believe all subteams have an STL/4540 student who know Python. There may be a handful of teams who have only a newbie who has Python experience. (Correct me if I'm wrong as I don't know all of the people who joined the team last semester!) If this is the case, I still think it would be cool to have newbies step up to helping the other teammates since it could help them build confidence. What do you guys think?

**Comment by jillianwhiting** [comment]
@kevinjuan25 @sgl38 @zam7  I like this idea, would it also mean that this will not be done during a monday night class?

**Comment by kevinjuan25** [comment]
@sgl38 I would say it's a reasonable assumption that not all subteams have someone well versed in Python. I think the teams that do have one - newbie or oldie - will have ~~an easier~~ less stressful time, and will likely not need as much help from outside their subteam. Teams that don't are free to try out the tutorials as a team, and consult me with questions. I can send out a Google Sheet for subteams to sign up for selected "office hours" close to the time when Python training needs to be done.

@jillianwhiting Yes, this would eliminate the need for a Monday night class for this. Instead, it will give teams something additional to do to help reach their 10 hour mark.

**Comment by sidneylok** [comment]
@kevinjuan25 I see. This sounds great! Thank you for putting so much thought into it.
@zam7 @jillianwhiting @jhs373 I think this also resolves a scheduling issue for our calendar as we discussed whether New Member Orientation or Python should go first. 👍

**Comment by zoemaisel** [comment]
All of this sounds good to me! So to be clear, there will not be a Monday night class required for Python training. Subteams will go through the training together and each member will complete their own tutorial with the help from people on their subteams and/or by going to "office hours" that Kevin makes. We will be very clear that we know that not everyone has an expert on their team, and the RA/Kevin will be supportive and flexible in setting them up for success!

@kevinjuan25 depending on your availability, the more help hours that can be offered, the better. We can even consider having team members volunteer to help other subteams and count that as an Outreach participation point in some way (@sidneylok @jhs373 @jillianwhiting). I really don't want people to who new to the team or on subteams with no experts to feel lost/confused during the training!

**Comment by kevinjuan25** [comment]
@zam7 Sounds great! The more people who want to help, the better!

**Comment by sidneylok** [comment]
@zam7 That's a great suggestion! I would be down to offer participation points if team members want to volunteer.

**Comment by zoemaisel** [comment]
@kevinjuan25  once you set up the google sheet, maybe the team leads can send it out in an email to the team to increase help slots as people actually sign up for help

**Comment by kevinjuan25** [comment]
@zam7 Will do! I've updated the syllabus to reflect the removal of Python in Monday night class. Additionally, I've put on the syllabus for students to start looking at the training a week before it's due. This should give them plenty of time to attempt and get help. I'll send out a sheet at the end of the week.

**Comment by fletchapin** [comment]
So this seems great for the Python training, should we try to teach people GitHub in the same way? Lots of people still have questions about GitHub issues, projects, etc. so I'm not sure what the best way to address all of those are

**Comment by zoemaisel** [comment]
Yes good point. I think that GitHub should be part of the same training if possible. Maybe we can add a part to the training to specify certain steps we want them to take that would involve using GitHub the appropriate way (ex: make an issue in github, make a new project for the tutorial, etc). Would that work?

**Comment by kevinjuan25** [comment]
@zam7 The interactive tutorial currently asks users to create and clone a personal repository, commit the tutorial file to that repository, and push their finished tutorial to their repo. For GitHub in general, they could reference the wiki, but we could certainly ask them to do more.

**Comment by jillianwhiting** [comment]
@zam7 I think we want to do a quick presentation about github so people see it before they try to use it. Could we add that to this monday's class?

**Comment by zoemaisel** [comment]
@kevinjuan25 @fletchapin @jillianwhiting Ok, so maybe we just leave the interactive tutorial as it is (do not add more GitHub information) but we can include an optional short presentation during this coming Monday night class to explain generally how these programs interact with each other? Not a focus on coding and doing things, but a focus on how they fit together to accomplish what we want.

**Comment by fletchapin** [comment]
@zam7 This sounds good. Basically I'll go over the GitHub tutorial that I gave the subteam leads to explain how GitHub works and also cover some of the stuff I didn't have time to get to like Issues and Projects, and then the actual pushing/pulling and practicing the concepts will happen in the interactive tutorial. Also I don't want to waste anyone's time but I think that making the GitHub presentation mandatory (then returning members could leave before the new member orientation) would be a good idea because everyone needs to be on the same page for the transition to GitHub to work smoothly

**Comment by sidneylok** [comment]
@fletchapin @zam7 I agree that it should be required to keep returning members in the loop. It is unclear to me if they have a good idea of the big picture of the transitions we're making this semester, so it'd be great to know for sure everyone's in a good place with the tools they have before we dive into our research.

**Comment by jillianwhiting** [comment]
@zam7 I agree it should be mandoratory for everyone is it still possible to do it for next Monday(2/5)?

**Comment by zoemaisel** [comment]
Next week, the agenda for Monday night class includes New Member Orientation led by the Team Leads and ProCoDA help (which I think will be happening throughout the week and not actually during Monday night class).

**Comment by kevinjuan25** [comment]
@zam7 @jillianwhiting @sidneylok @fletchapin I could quickly go over a few slides to show how everything will be connected so people can understand why we're switching, and Fletcher can go into his GitHub tutorial.

**Comment by janakshah373** [comment]
@zam7  ProCoDA help will be throughout the week and we won't have that long of a presentation for new member orientation logistical information. @kevinjuan25 @fletchapin if you guys want to take the first part of class for Github, then go ahead, as returning members can then leave afterwards.

**Comment by janakshah373** [comment]
@kevinjuan25 @fletchapin When you guys go through the Github tutorial on Monday, can you make sure to show the team resources repository so members know about that? I'll send it in an email tomorrow, but this is just so they can see it firsthand during class.

**Comment by fletchapin** [comment]
@jhs373 sure I'll give them an overview of the team GitHub page so they know where the tutorials and other resources are found before I explain the basics

**Comment by kevinjuan25** [comment]
@jhs373 @zam7 @fletchapin Ok so we'll start with [this presentation](https://docs.google.com/presentation/d/174NIBBmvKzjiO3z9EPHVLyeVCMWWj2mpWMXQmfzNo5s/edit?usp=sharing) to show people how things are changing from before and how they can learn about the changes. Then Fletcher can do his GitHub tutorial.
