### ISSUE TITLE
Transfer "Common Errors in Python" tutorial from Github wiki page to Sphinx wiki site

### ISSUE THREAD

**Issue by HannahSi** [AguaClara/aguaclara_tutorial#51]
The same task in #49 needs to be done for the [Common Errors in Python](https://github.com/AguaClara/aguaclara_tutorial/wiki/Common-Errors-in-Python) tutorial. We should transfer as a new RST document to the `aguaclara_tutorial/docs/source/python-and-hydrogen/` folder.

**Comment by elenapertsalis** [comment]
I have started this task and will finish it soon!

**Comment by elenapertsalis** [comment]
I just completed this issue and created pull request #53
