### ISSUE TITLE
Travis-CI not building for aguaclara_tutorial

### ISSUE THREAD

**Issue by HannahSi** [AguaClara/aguaclara_tutorial#52]
Travis doesn't seem to be building for the last push to master. Under the [Requests](https://travis-ci.org/AguaClara/aguaclara_tutorial/requests) tab of our Travis page, there's an error message from the gh-pages branch saying "Build config file is required via repository settings, but config is empty." This occurred about a month ago, the day of the last working build. I don't think anything changed in our .travis.yml or repository settings during that build or since then.

@oliver-leung would you have an idea of why this is happening?

**Comment by oliver-leung** [comment]
Deploy has been [completed](https://github.com/AguaClara/aguaclara_tutorial/commit/5612850e7089bd4d8932888488caba7b2e48933e), and [Travis](https://travis-ci.org/AguaClara/aguaclara_tutorial/jobs/515756314#L623) looks good, too.
