### ISSUE TITLE
Write Colab tutorial

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aguaclara_tutorial#54]
[Colab](colab.research.google.com) and Jupyter notebooks have proven to be a a great alternative to Atom/Hydrogen/Markdown! We should replace the existing tutorial articles with a tutorial article on using Colab and moving files between it and GitHub.

Another thing we should change is moving all of the interactive tutorials into Colab notebooks, then exporting them back into this repository. Then, users will be able to copy them into their own GDrive folders and work on them without changing the original files (and also avoiding confusion on forking the repo).

**Comment by HannahSi** [comment]
Wiki pages on using Colab and interactive tutorials in Colab have been added to the repository! The wiki has also been updated so that articles about Atom are archived and articles about the AguaClara package reflect its current modules and import structure.
