### ISSUE TITLE
Update Git and Github wiki pages

### ISSUE THREAD

**Issue by HannahSi** [AguaClara/aguaclara_tutorial#57]
The Git and Github pages in the wiki still have references to Atom and cloning/navigating through the `aguaclara_tutorial` repository, which is no longer required to complete the interactive tutorial assignment. There are also garbled or missing images in some of the pages, and incomplete information on merge conflicts. 

We should 
* remove the outdated references
* make sure that all the proper images are provided (fixing/replacing those that are garbled and adding ones that would make the tutorial clearer)
* fill in missing information on fixing merge conflicts

**Comment by alicezha0** [comment]
Added descriptions and clarified confusing terminology on the git and github pages

**Comment by alicezha0** [comment]
Added clarifying photos where necessary and replaced old photos.

**Comment by alicezha0** [comment]
Changed photos; Moved mentions of Atom into archived section

**Comment by alicezha0** [comment]
Fixed photos where they were case-sensitive. Documentation has been updated on the wiki.
