### ISSUE TITLE
Links to utility functions in Python Tutorial  don't work

### ISSUE THREAD

**Issue by Thomas-Bradford** [AguaClara/aguaclara_tutorial#9]
https://github.com/AguaClara/aide_design/blob/master/utility.py

I'm working on the Python Basics section of the interactive tutorial, question 3, and I'm trying to find the functions from the utility module in aide_design. However, the links given in the AguaClara Python Tutorial to the module's different function's aren't working.

**Comment by kevinjuan25** [comment]
Fixed
